language: python
sudo: false
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - 'pypy'
env:
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.11,<1.12.0"
  - DJANGO="Django>=2.0,<2.1"
matrix:
  exclude:
  - python: '2.7'
    env: DJANGO="Django>=2.0,<2.1"
  - python: 'pypy'
    env: DJANGO="Django>=2.0,<2.1"
install:
  - pip install $DJANGO
  - pip install -r requirements/dev.txt
script:
  - flake8 *.py django_markwhat/*.py
  - python run_tests.py
