language: python
dist: xenial
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - 'pypy'
env:
  - DJANGO="Django>=1.11,<1.12.0"
  - DJANGO="Django>=2.2,<2.3"
matrix:
  exclude:
  - python: '2.7'
    env: DJANGO="Django>=2.2,<2.3"
  - python: 'pypy'
    env: DJANGO="Django>=2.2,<2.3"
install:
  - pip install $DJANGO
  - pip install -r requirements/dev.txt
script:
  - flake8 *.py django_markwhat/*.py
  - python run_tests.py
