language: python
sudo: false
python:
    - 2.7
    - 3.5
    - 3.6
    - pypy
install:
    - pip install -r requirements/dev.txt
script:
    - flake8 *.py django_markwhat/*.py
    - python run_tests.py
